Download Button for Plots
sharp-lilac/shiny-tamr-app-uberi pull request #66
Opened 2024-11-14 00:21 UTC by Konkaseeti

Download Plot button added to Coral Health Explorer > Dead Coral.

Changed the Plot render function, It is now first created as a reactive object so that ggsave can utilize it,

Then passed to renderPlot() which will still place the plot on the UI.

Download Handler function added for the plot I was working on as well.

2024-11-14 02:29 UTC, sharp-lilac requested changes
Nice work! Just a few edits. I appreciate your contributions to the project

2024-11-14 02:29 UTC, sharp-lilac commented on server.R
> +    coral_health_plot <- reactive({
Good solution - this works well, and the app still runs fast with the reactive expression

2024-11-14 02:29 UTC, sharp-lilac commented on server.R
> +    )
Perfect, great!

2024-11-14 02:29 UTC, sharp-lilac commented on ui.R
> +                                downloadButton("deadCoralDl", "Download Plot")
Could you please name this ID based on 'snake case,' which an internal styling standard we have at ERI? All undercase, separated words by underscores. For example:
`coral_health_plot_download`
Once you change it here, you will also have to change it in the server too to match. Thanks!

2024-11-14 02:29 UTC, sharp-lilac commented on server.R
> +
Please add a section title, for example:
`# Download coral health plot`

2024-11-15 19:44 UTC, Konkaseeti commented
Did the mentioned edits. Commenting incase.

2024-11-15 19:59 UTC, sharp-lilac commented
@Konkaseeti Did you commit the changes and push? They aren't showing for me.

2024-11-15 20:04 UTC, Konkaseeti commented
I did, I cant make another commit without making a change

2024-11-15 20:42 UTC, sharp-lilac approved these changes
Great! Thank you, found the changes

2024-11-15 20:47 UTC, merged